address = "0.0.0.0:8080"
environment = "development"
database_path = "./local_database.redb"

[[cows]]
name = "https://moooo.farm/cow.txt"
character = "brave"

[[cows]]
name = "https://bark.farm/cow.txt"
character = "shy"
